### ISSUE TITLE
Option to display ordinals in dates

### ISSUE THREAD

**Issue by SYPOMark** [justintadlock/clean-my-archives#4]
Hi there,

Thanks for this very simple and easy to use plugin that I have returned to repeatedly.

One thing that we would like to see, if possible, is the display of dates as ordinals. So, if an article was published on 2016/09/03 it would be displayed under September as 3rd Article Title, rather than 3: Article Title.

Apologies if this is the wrong place to be asking this ...

With kind regards,

Mark

**Comment by justintadlock** [comment]
Date/Time formats are a properly handled via translation files.  The `d:` format can be changed to `S:` or just `S` (without the colon).  Of course, that probably doesn't help if you're an English speaker and likely never done a translation.

I could see adding in some date-formatting parameters for the shortcode though.
